# Generated by Django 3.2 on 2021-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogViews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpost',
            name='fpost_date',
        ),
    ]
