# Generated by Django 3.2 on 2021-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogViews', '0002_remove_fpost_fpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpost',
            name='fpost_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
