# Generated by Django 3.2 on 2021-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogViews', '0006_post_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fpost',
        ),
    ]
